// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdUZ7gwiKWrCaRF_SmPknLP4bRylQQNk',
    appId: '1:676557407765:web:1995889931c07781edf01c',
    messagingSenderId: '676557407765',
    projectId: 'grupchat-cec2e',
    authDomain: 'grupchat-cec2e.firebaseapp.com',
    storageBucket: 'grupchat-cec2e.appspot.com',
    measurementId: 'G-XYDXFP6C8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcbKnTTkPMhs1qdG-iX-mfnSosGQUED8Q',
    appId: '1:676557407765:android:dcbfd93055c0a07cedf01c',
    messagingSenderId: '676557407765',
    projectId: 'grupchat-cec2e',
    storageBucket: 'grupchat-cec2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqlruA0-V8P0nZ7RVR_oFMs-yOuJBJQs',
    appId: '1:676557407765:ios:110fc74f6993400aedf01c',
    messagingSenderId: '676557407765',
    projectId: 'grupchat-cec2e',
    storageBucket: 'grupchat-cec2e.appspot.com',
    iosBundleId: 'com.example.grupchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArqlruA0-V8P0nZ7RVR_oFMs-yOuJBJQs',
    appId: '1:676557407765:ios:c89aab037bf88209edf01c',
    messagingSenderId: '676557407765',
    projectId: 'grupchat-cec2e',
    storageBucket: 'grupchat-cec2e.appspot.com',
    iosBundleId: 'com.example.grupchat.RunnerTests',
  );
}
